sudo: required
services:
- docker
language: shell
dist: bionic
arch:
- amd64
- arm64
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/arm64 linux/arm/v7'
  - TAGS='latest'
  - secure: Zdo/O58Tm47iGcSDC4QbVmdfi1KUzkge1ggwtm60/lWnkCyt3vxtSTvRFdetpUzNHbANADfjA5KXCao8pNWwcD9TufcoWh8FCU6IBC/46GsJRRELmCLC7SmSimBER0V/KRkT0wkEmgLXwTHuc4/q7PqUWvOm/M2GpAqRy3U1tZGDXNzltbad2mIV9UfD65MV4AOAg4L5HENUGjJ8Yrb7vyclcHCWZawPLzcgv0qEmsxfa1aPhDyfrtav95XSh8FnDJDs+571WesOPOjWeZUpw1TzNdJKctJbYFTFNeYdLmctn/gBAE1bgKqyIRxtaqOkZJTgcV+7GNmVGz2mei7T+B6j49rpoPMi9djUvHyaLG5n4EcjaquUHW0gS69UvhZm/GO5I8lT2RcfmnkiHrYWeE74MkHdklD7TpqiTjpOcqR/OPKKrPB8giBJFGaXqJKC7uJYg0s6kLZASWRLi4fr1nhOOuOuEQyNj236A7qdR4A1rGYijC0ffaDHTF9pVBQa5x5cbsKbmKlyL66SCzilgJUapjRF8agy4+leg2pedylCvvd+8eCk1eUoJsqkledLwLvWki+s4p8e96Yp5hE7MPTx1793sHqOc9A2i2HEJLhfYcTYTiLnTd+z4NrKB3IkvvpyhaVjiMR2P4KKBH2n/umWPGiP2zqe+1ehQsEqMeA=
  - secure: KfXEB0P91hcNdUHCmy+LUYY28r3LX/YdTj2KeLTWIGF+PdBRWnNu1Nen+pn/hC/FmKvmw/bNOymq39nQRcOqgKhDFbUjZ9p0tfm3zkGicEJmCTp6Ncz9mYhYrp4LJy7rgGr8olxcWB/gsm61EodmJ4wSzMt3dzosp9UQaNiBz6tiSn/pyttWv7M3Z5ZijTxiQvpNlGLBAcqhaqrFD2owk5Ga+I/isCLNnJ6fwL3HFmtvye1+r5TOPq9dtx3NLKe8UQ74Ns7BOfAKIYZSP3P6cgfLEjYblERl13ZDloBwDlCGYGvVlOTNfvwRo/LUjTDGEPqF4mGBSSNnEXwLxLt6CUZd8Olz+GjY0fTjldbLyFZElNokwHimZclXY5BDMxzWRkfZq92cghqtVJmXqJEnQaq4+FzISj24YqrwhkNmAYpsof2pwvlGyF0vJ4KBdPPMm0ABxi1vuPoDxN8s/33IUkPIh+5TZeyfTEdv4SkpeylOM7v4ujLksuoXL5QDwsG7f4OQo6cbNHkeghZPVndUhZKhzFIrrQJWKBRV5XbtcERtdJePAUQ1R/SnMWWp6pf81ygSk3KXj7lY5X0c4CRxFJySlq3k/8ro3Kp8MfcQ8g0FGqgCOHJaHzj0EPlNCQUBMI7jyK8iA9943gX5UE6bjKUYEE+GKSnLrezV+YnmDMI=
  - secure: G2dtMoXYAA5EfxLHzZWrU0ZE5KRY+gBt5Ktx/qMhM+15pPSJwITGMeZvHVEc0id9nczzVbxAmviqpAi9j8sb9YuNdVBQKUbzdTwt/AflwfcY6ho0FK3cNAZHQnHJ9A/Bh8rZcHtG4M8UwPFkQcMVxxHm/jsil0Ao+lkz3Qom/bjSLwDle6xUGJVB1KxTegtFSNbzV4Nr7IA8FSpE+/drXODBHoiVT7xIrX1ikJ5KKho/fyfK/LguI+M08YUs2Yapq7EO6khwiQo2t58jpkCHqEx+nEkoElhcDhSf6qd/yGt9wplREeX5aklo7QLsyalUG6lZR6iGX8b3i+GWMRdEwe4RKhu0bZrpEpzO5PN20CuAJYhtMF//BPBE6R0fvcNuftMBO1qilJMf3L2qmAIRQy6zNKhR5elg1RI+M+q/zrCFOkWobhqNIZadDWJhdk1cfECzayq3DHp3Cl4c4ecLo0B4hE1TVmQokG7MQGMeQAxcdm5Ytc41s7Ukim+L17NrmvgjqvI3xXAMhUPfIWGI7fkcStQhvdaz8T1BZLG7puXE0jVpJtBfiYlZpjIiRbtLtP1FeP1mLE4uajNZO7UXr/fpfupHsRPL33xanCqO6f2XJn3Vl6kfoaoL+xVy3aFWFYQvTqPTacdnZDVyP4B8ICZo8AVAfKC+Xvp/sCyX3J4=
jobs:
  fast_finish: true
  include:
  - stage: Deploy docker image
    script:
    - source ./buildx_ci_images.sh
    - set -ex; setup_ci_environment::main; set +x
    - while sleep 300; do echo "still alive"; done &
    - set -ex; build_ci_images::main; set +x
