sudo: required
services:
- docker
language: shell
dist: bionic
arch:
- arm64
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/arm64'
  - TAGS='0.1.3'
  - secure: E703b1zmLfv/g/Q4jc9XTUdNjmwaFwjSOQJzS/zqYorskNTBrCb6DCFNrGkYJZ8gS4SSI7AlEHLEdYmldNZ8EYDvuhKHQOOuKywG6po0vRuItGogIVqIZU6SyV2Yd3lrQN7BFFF4280s/zNNlwQgL/1jK4h0cWT3fGGDiNbyRfglJ9y4hzKh6VqoM5TyBWQXLtFwyUDZ8QbggkTPMv/btRYI7taR/UkiGAQJyv5gjubOXQ4NeZUvpS7ps9FY81XNXKnE7bmgBhAFI92+MeSmQXI8z9i06vCkMhIptcz6h9YgCF7x3uMG8+rsoFB+mWUGOuSYH4w8N00g/P+E1yk7vdNtMhmwnut30axoV6JmSyzJeHQsw4Ge9/zkfGHhxUWLy8wcJBSJ2F5P2MlJEzrRbLcWMTGRU7+AQXWk64ST3ptjVZFWGkZl6KSbZ1izW31M3W1zU84LayD64Sg1VtY6CBxfRIWsGonlbV6RppTyPEMa3zF50HuScUWfjv7Juh2zQTMbOyU0BxxgmGqExHVRYS1/9cjPAiehewwubbc0G7h0n1j5CC2GnwNezgRTaIaDbK0TOTP1pEtkv8hSmU2EkcYX5v+jh6wosSMBXJD9ibtwcSXY+7UXKiz3UcwTLmkoSrmVq8LoNTk4v44waJJjEQcAojkvrQQ0yjGGOS5nA9U=
  - secure: Nq6/kroYQXa9Fz9QrHdmq34bkX1CSEqrmyM36R4Ip5mA1bLBv0o7xnXDa1DLL3Xp0RJUZtKhPRQ33XBOHj4XvEZYfsCnKpPygXTDpW+/2p4fMGvGF/mHm3LfktjhtHDUphwrVGlHSyOs6d8HPbdzwEPv/epN+IFC84VC+24jA18UjKzJ5AqFA+uNUfCI9FKW/fJJVVVBYGil1q6rFX3H7WllO/GE32vMzjGXuwnrPaGioUqxe4Pp7Evq3qOwDJEtT7OI3dtiCZHYgENufsPMyDjR9AHyjkhpA1PLz0mygtE3DGGayqAX6S6QBwW/ddRKqpRFaJbBSIy7PIEuHH7LsJcMLvvYeBDZxaCuJ/fdoMBU9tfExxUWXLON9QPxIKimuJ3EDk25XQPs2uY9XlffCOptI5g2folUt+T6DVbic+OLQi051VXBruJKrmVjGsbQ0sreEb/JH1Qp9yOTFYLaOrZGD3qy5R0OgfO/mkUuvolNekeTw3nM/mNSmqTky1wtvm/XwsrJYsB5fUk5VK+rnpmX5I0m/XFvnE5QKkZ3T6e75WaF8iqU2om8PlEuKfAk84ErLPd7K4kNUqhXVjnXD4C1cULcklRB/ACDM/Mq1XmvArb1zN58Aj9IenR88yGX61TL9ZANFyp7tVaOoIWxRoj1YO/0asGyvKerAFFQmW8=
  - secure: hWhxSLaLvxnQBTDx8FpISNUuWTWB36rJt1N4kq3VrVQNgARMIJTon8LH+9QegM+BFae0RYtx3+a7NcLIPRctQNmfFXjN0ETnGerEWzygdSQFuCGdHaZ2nK0HXoYBtQuUsz79lqxW+gz4VQCECvzeGQQeb6vs7K0P2/ZYk2t7BvzBxWQ0r7g4+DijIrcIp5PcGtldCg7Fos8fyRBw4vJWhrgUAOO3KHtBq/FycXWu95iVXlOXAoxVdA0dtkVkZvW0DtJUD3NjfkZBIqYHZrva4Z6YrQKbe+viFzWRYVLLKZY6sq3OgezvGiytpiDasYiTxg8VKQ1bnuacPdYziN5hAZjbhO/4HipkhzrhR2AGY+VHNm090H+Pscfn9+gze8DmEmlzyDGx7FybyX8tQgHBtdux9+3/DlKFiONhba23db8k9z7rNhVkvC8dXtOfCmY05KErgU1pqq1D5mtNIeUW/gyiH3LcC61jIoIT4/RvYXCpXnVU4T+4iRH3zZIn4NqqsJiFvBXFbP1Id3nz5ipyxe2BWOUcNqdy3xmwOJ9CadMhaAC6kdAfOto0b3tlpK2Dnx3QCbShqRph3sfjvhtZVpVaFG2u049w5beHxNOxcCGI5J7wvJPiD8D1WXXSduGmgeDByDEqUBJ4p7Q7OX7iZWx76IAmYMotuJkbVuvCVUo=
jobs:
  fast_finish: true
  include:
  - stage: Deploy docker image
    script:
    - source ./buildx_ci_images.sh
    - set -ex; setup_ci_environment::main; set +x
    - while sleep 300; do echo "still alive"; done &
    - set -ex; build_ci_images::main; set +x
