sudo: required
services:
- docker
language: shell
dist: bionic
arch:
  - amd64
  - arm64
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/arm64 linux/arm/v7'
  - TAGS='latest'
  - secure: APbOJfnsyUjksmS4aCYueq+TjV8miQiSpFFg/EeIDfbM7zTnSHS/TE/SDkn9r1kW1KND+SICdzD8of7XMfrKTXSr1al19z+uSg7B9ET7aF36ROzSZh5faf1Ml6rePlarzkb3DyJ0NewL3PmHyrwNc066VzCORGCCWRg7/ZXwbp2lCFD9nfKlK7CbW+LuoZji9DBHK0T597l0/lV3AoH6cCNqhUseoN9wyiBQyNs9OxGWP9FdADmP8zsCXUVo76Up4mA+jdavE5jxS9fLpXOa5CKL7LD+7REKdUXWRyAfpYkWX6s6R08Yhkl3ma85rQ/nFs78UDnt3Nrcl6hnOxBEqEyFZCCXX9oG8Nd7ULFNvBMDGGTQsO8FjnMjhHPKSzVA8QUAVrgVhJOCuGlC9X5bUc+GkHNfZmudBs1lqls2iPJtwSDSRca0iBLXIANIf7qcEb6etr7Q6EhEHnqsaW97ZXn1VcOQGcujJlK6HX/QVQ10Yq0fMAMwG1TUBXcKw+qJfK2u9rIkbCly4FJ7A/jj5fW0uwNjCNQDOMstNlSLCpRbiT5QljPtMWO2cUPBe3Vti/xtcJ+CDQlMgYU6eNg2sjGse1xZ22VwpbFlSCOC2V8KluTApFhqi1mDH4z9Y23gB1xhbij58l66MqlQigjcsSEmH02lkucuHXHp+z2P7ZE=
  - secure: nvLUIzuNUZu/cXpSTouWniVru+UP4K5UcMPShi5l16PGgZvYBSpzV6rRJoBBIj470bE8ZXMxjnq7uOxlq+eRwrAHgrptGpkDS+1d5QKE6nRwBseJ/z4xaAqeOCjQdgg0gvNn0fDrslgZAPwfK/nStHak86jJrI/E0UhpspCnvGUByri8BYOiudOIXhe/W1NHzhgbNoTfN6yxQmcFWHnGyHhsNRyPX934Qta/6N1JUrFwpbmmk/qxNi+Jco12fERtW9kd5sFadVixlms9yrlt7cgnaP/a+6SGr0eY8b1itPtTaUIQKxASJKsdBNgZ7LEUheLhrbEjutsAN4Muh5F8n+c95+ptZsno1MloOVo7UKGqC7/LECSFV0eponAzEStb/55vBYE1PC8lwHeLVfF2DWlgrCww9tQ7dV1R1SMR2Fu4a3GckJyBbNORhVzgfP1dxt0+yG4NEzXy7jHcFBVEY3e0mjROdU141ysSiOLcpekV7UahNRWrNLQMK7TO4G/uM5bbkdMiaRGhDfp0roytqROghXG1pxx6GKH6xTUZtxSK4k9TqbUCiRAjmATnkrrz6Y58nBIVXMMX9ySwZTiu7fqfBIRNYSYi/+yu9/Ws2/FziHaepdc2/miNI1S6bNIGdIyxjvC4h+JlaWWKvCHvmaGtC6skRWh0zCZ/91Kp92w=
  - secure: Z3IRGbBa3i7av05+fv2V6tJdAh50lMryjQRMVwKlWWFWV3bKnaVupTN0CxTUJ6a5PoF+fMgI0UmMeX0jVN7Iz7ntHxHsKFS3urXENZIfbYVhoWH5Y130oWxUe8MiI2KxnEaG5Cfw9ulkDvq0NY2oi0AUz11XZw/y2JbKXgpjs/NVVgw62KXyRI6c+JdxKL+pqGTfmxn5kqgKlO692ayVJ1cvTLmVzf9vvR6vK0XjD0feKYLCvo4qJrPfKbz0oBBLmgHCOmyrZ1H6oWZ6WL63GoN62oOBuAdgPCzGM19JIaAo88xmi5qFlklgF3hErnJsLSNgvZQy+i8Ezq8jFh2rv94e9KV8bwivSYzIHW0PTo5wVmuP1TCwN0a9ipa9k7YQ79Vx+r7wY04O03IDPi6P0VjhIbAEP2NcPXoEq1uQxIXgMPqp2LOmlm7eb7pPqcTSAi1M8q2tG7hapjtCjDgdS3aIWxTMOKVUvvbjKn1+VAK4CGumIWmCmeGWPrOP2lRolxwqtW59fkWAbc5v2CEpJkH3ABuKKI1xKYhDEk8qY1B7YHtg/i9x2ePb9fc52kQ+ebnyM3Fs1WSkOVABJsP2x+rOcVJSFU/yYUhm4jYefVb79GftB2fpcrrgcru25tnduP0TgwwYGhpQz1VnMQiJSXCe4G1pCSh9KlODdH/CIRc=
jobs:
  fast_finish: true
  include:
  - stage: Deploy docker image
    env: DOCKER_SLUG=$DOCKER_REGISTRY/$TRAVIS_REPO_SLUG#*/
    script:
      # Install build environment
      - source ./buildx_ci_images.sh
      - set -ex; setup_ci_environment::main; set +x
      - while sleep 540; do echo "still alive"; done &
      - set -ex; build_ci_images::main; set +x
