sudo: required
services:
- docker
language: bash
dist: bionic
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/amd64, linux/arm64, linux/arm/v7'
  - TAGS='latest'
  - DOCKER_BASE=$DOCKER_USERNAME/librespot
  - secure: Lb1oUy5xIWjco6WAxnh7AX0tFUC5R4h9hFQ7I9r+ruM8zHx5eRpn7Dx0B9n4IR86TGyk5f4LmTUqqADdKDdu36i4/L1QQ75oyvwt/cebkTFATIQ06xuNJoxIWRYq7GgfFeyy3YtE32OVYPa7+pDI0Nll+mU/U/gjf2BhgGpWEABmcxSBMuilrgO39zi+P10mQ8rBvpdWGumG0n+6QCKq33YQ75oQD13fMvmtFWBpm4PF+FzrdvG1/6GoaS3tdRODQwJywdeJmuMD7aGnC45zI+q/AyYgDNSp0F27cjJTdv7BrWZJxvrZYwh3q38MfqzOtmNV7Q2bClG29woDnIM0LBnaW/w2/40dPuzs2VVcPpHI8qhm1Jrz4juja8cOMYWDkuNcKDSIRjlKReg4QsYR8cvjCrTqTTdqBIk/b0bvRDzqX+m/BTaDuE3aZOgV2+9IYwxw9XJqvlnqj74nwgsqFWEU57LmWjQZyy1nL+sEuwOC3zc8tTFA+KSobDCL2++L1YPu7YI1N+Siy9zYVMPsjJVv9LBlAS7ujqszhf2+XwdyUDUyT18pfHRKsefslVnvfmI0PZoQAYd9LBNbRhwmnIex/5VgKC8w9cq3A1qJu325l2Q8i9gjddYKcK3HgPeUajoWKApPJRU4w8XO9or7QFE+ZuQ391esxa7Nv4d/6IQ=
  - secure: MDJqGrO6TxNTWmfi3X1ZSvJlvuqM4kIGydEyIOH+qbc44h9wP05GvPnAGihgu5vXYoKBkIioIABTWVRsNhAJpeLkhhYB2Z6/ru4+WMpAWU7CR0kvnEAZ1z8CXs8as595qBFJAdyLkpxFAo/JHiq5gX14Z7RoJIrFoqgOU8S0rqxGTqgLWPmTkhSw7w30R3JFj95N4pgKg5r4JwtNGj3I4OeM8KyCwuagcqNB1NCFKXqVCNVPPN3q6I/Dsx7tg+vulw1Zt1oGEQTm1WJZIP5I/53owu629tllB8txhOOzH+KWzga57sTQAgtlEV3i7Bs8QyeOBfFEq2SF7CILbQyUnlpir7W/FBKt7+Y5So+4RiukJXwfE5zfUj14f9m5jp22rDSgDrWVgt4l65DZ5o5EbQ0XkjVF50vtKi+yXWxghLIJJYaxqZ256GaLIZq92ixfz30DPhujxlEkGAZNHAQn8xpAt/UwHAZBTActoSirTWr+IwkXe2WC8qOoZcFQ3KiSh24Fx5qBGbSIrWJwxCuW1tFx3Gy03XxDd0Veyn0BuDh0OP1f5rKw2EU2M5CdPkNa6qB3tVCLA3Wn+eoDST6n/EByT2ZuoEB1EC58lFFQxp2n12iPD+Tu9/QseMJCYRQZo5Xxprt2cpkvXeyGH9BM9qCdn0Wfd7Ou+T13dCdjsAU=
jobs:
  include:
  - stage: Deploy docker image
    script:
    - source ./multi-arch-docker-ci.sh
    - set -ex; multi_arch_docker::main; set +x
